name: CATCaller
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py36_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.1.1=py36_1
  - python=3.6.10=h7579374_2
  - readline=8.0=h7b6447c_0
  - setuptools=47.3.1=py36_0
  - sqlite=3.32.3=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.7.0
    - affine==2.3.0
    - apex==0.1
    - astor==0.7.1
    - attrs==19.3.0
    - basemap==1.2.1
    - biopython==1.77
    - blis==0.4.1
    - catalogue==1.0.0
    - cffi==1.14.0
    - cftime==1.0.3.4
    - chardet==3.0.4
    - click==7.0
    - click-plugins==1.1.1
    - cligj==0.5.0
    - ctcdecode==0.4
    - cxxfilt==0.2.1
    - cycler==0.10.0
    - cymem==2.0.3
    - cython==0.29.3
    - cytoolz==0.9.0.1
    - decorator==4.4.1
    - dynamicconv-layer==0.0.0
    - easydict==1.9
    - edlib==1.2.3.post1
    - fast-ctc-decode==0.2.5
    - fastnlp==0.5.5
    - future==0.18.2
    - gast==0.2.2
    - graypy==0.3
    - grpcio==1.12.0
    - grpcio-tools==1.12.0
    - h5py==2.9.0
    - idna==2.9
    - imageio==2.6.1
    - importlib-metadata==1.6.1
    - joblib==0.15.1
    - keras==2.1.6
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - kiwisolver==1.0.1
    - lightconv-layer==0.0.0
    - mappy==2.17
    - markdown==3.0.1
    - matplotlib==3.0.2
    - minion-data==0.2.1
    - mock==3.0.5
    - more-itertools==8.4.0
    - murmurhash==1.0.2
    - mypy-protobuf==1.3
    - netcdf4==1.4.2
    - networkx==2.4
    - nltk==3.5
    - numpy==1.16.0
    - nvprof==0.2
    - ont-albacore==2.3.4
    - ont-fast5-api==3.1.5
    - ont-tombo==1.5.1
    - opencv-python==4.1.1.26
    - packaging==20.4
    - pandas==1.0.4
    - patsy==0.5.1
    - pillow==7.0.0
    - plac==1.1.0
    - pluggy==0.13.1
    - portalocker==1.7.0
    - preshed==3.0.2
    - prettytable==0.7.2
    - progressbar2==3.47.0
    - progressbar33==2.4
    - protobuf==3.6.1
    - py==1.8.2
    - pycparser==2.18
    - pykrige==1.4.1
    - pyparsing==2.2.0
    - pyproj==2.6.0
    - pysam==0.14.1
    - pyshp==2.1.0
    - pytest==5.4.3
    - python-dateutil==2.7.5
    - python-levenshtein-wheels==0.13.1
    - python-utils==2.3.0
    - pytz==2020.1
    - pywavelets==1.1.1
    - pyyaml==5.1
    - rasterio==1.1.2
    - regex==2020.6.8
    - requests==2.24.0
    - scikit-image==0.16.2
    - scipy==1.2.0
    - scrappie==1.3.3
    - seaborn==0.10.1
    - sigopt==3.2.0
    - simpleitk==1.2.4
    - six==1.12.0
    - snuggs==1.4.7
    - spacy==2.3.0
    - srsly==1.0.2
    - statsmodels==0.11.1
    - tensorboard==1.13.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.2
    - termcolor==1.1.0
    - thinc==7.4.1
    - toolz==0.10.0
    - torch==1.2.0
    - tqdm==4.47.0
    - urllib3==1.25.9
    - voluptuous==0.11.1
    - wasabi==0.7.0
    - wcwidth==0.2.4
    - werkzeug==0.14.1
    - xlrd==1.2.0
    - zipp==3.1.0


